### PR TITLE
Sign Up page added

### PR DESCRIPTION
**Pull request by KISHORE-LAXMAN**
Screenshot 2021-08-17 at 9 56 39 AM
Sign up page added in responsive manner.

### CODE REVIEW

**Comment by kiruba-r11** [comment]
@KISHORE-LAXMAN add padding at the right end

**Review by kiruba-r11 — CHANGES_REQUESTED** [review]
Add padding at the right end

**Comment by kiruba-r11** [comment]
@KISHORE-LAXMAN Upload the updated screenshot

**Comment by KISHORE-LAXMAN** [comment]
Screenshot 2021-08-17 at 9 56 39 AM
padding added in form part of sing Up page.

**Review by kiruba-r11 — APPROVED** [review]

**Comment by kiruba-r11** [comment]
@all-contributors please add @KISHORE-LAXMAN for code

**Pull request merged**
